### ISSUE TITLE
I keep getting an error when i try to compile it looks like a syntax error

### ISSUE THREAD

**Issue by Luqmaan2** [KalleHallden/exer_log#104]
![image](https://user-images.githubusercontent.com/73324519/185746269-7b15b062-53b5-476e-9349-b2a614ec2976.png)

**Comment by jorre127** [comment]
Think this is linked to pr #105 a PR was merged that replaced the colors in global.dart with a new system, problem is right after that another PR was merged that still uses the old colours, seeing as they don't exist anymore you now see this error.

**Comment by jorre127** [comment]
made a PR #106 that should fix this.

**Comment by Luqmaan2** [comment]
thanks
