### ISSUE TITLE
noNetworkConnectionSnackBar.dart Error

### ISSUE THREAD

**Issue by TheAmanM** [KalleHallden/exer_log#116]
`noNetworkConnectionSnackBar.dart` currently contains the following code:

```dart
import 'package:exerlog/UI/global.dart';
import 'package:flutter/material.dart';

SnackBar noNetworkConnectionSnackBar() => SnackBar(
      backgroundColor: redBackgroundColor,
      duration: Duration(
          days:
              365), // set to a year so that it doesn't disappear automatically untill the user clicks on the Dismiss button
      content: Text('No network connection, please check your connection'),
      action: SnackBarAction(
        textColor: textColorBlue,
        label: 'Dismiss',
        onPressed: () {},
      ),
    );
```

`redBackgroundColor` and `textColorBlue` do not exist in `global.dart`

**Comment by mfederowicz** [comment]
Hi @TheAmanM check https://github.com/KalleHallden/exer_log/pull/106, we know about the problem, please be patient :)

**Comment by ramsy0dev** [comment]
sorry i forgot to do a push to my global.dart that contains the  textColorBlue and redBackgroundColor values the issue well get fixed in  #117

**Comment by TheAmanM** [comment]
Understood, thank you! Should I close this issue?

**Comment by ramsy0dev** [comment]
By the way i looked into the pull requests that got merged @jorre127 when he did this [PR](https://github.com/KalleHallden/exer_log/pull/94) he accidently removed the colors from the global.dart file and his PR was merged after my PR was merged, and that cause to  `redBackgroundColor` and `textColorBlue` not being found

**Comment by jorre127** [comment]
For anyone reading check discussion in #117 for more info.
