### ISSUE TITLE
Readme buggies

### ISSUE THREAD

**Issue by PickleNik** [KalleHallden/exer_log#118]
<img width="423" alt="Screen Shot 2022-08-20 at 4 12 35 PM" src="https://user-images.githubusercontent.com/31113245/185764568-689b36c6-cb9a-405d-a18b-8c3a867ed774.png">
<img width="466" alt="Screen Shot 2022-08-20 at 4 13 13 PM" src="https://user-images.githubusercontent.com/31113245/185764582-f053464e-f9ae-4225-8776-d931d507db0a.png">

Seems like the shields.io badges don't like to be centered in the Markdown syntax, HTML <img tag is needed instead
Also, the bot defaults seem to have messed up the link again.
I'll make a PR with fixes in a minute

**Comment by ramsy0dev** [comment]
you can use it as an image instead and redirect the user if he clicked on it to an other page using the ```a``` tag

**Comment by PickleNik** [comment]
> you can use it as an image instead and redirect the user if he clicked on it to an other page using the `a` tag

yep, that's in #119 PR and added to @all-contributors bot template in #120 

(edit: I reread, not exactly another page, just changed Markdown syntax that didn't work inside a `<p align="center"` to `<a href="#contributors>` and `<img src="shields.io" >` tags that do work inside the *p* tag)

(edit 2: #107 already covers stuff done in #119 and more so I closed #119 in favor of #107 )

(edit 3: reopened #119 because #107 had bugs)

**Comment by PickleNik** [comment]
Also submitted a [proposal issue](https://github.com/all-contributors/all-contributors/issues/615) to change allcontributors bot's default rc to not have a borken link by default. Upvote if you'd like
