### ISSUE TITLE
Firebase Features Suggestion

### ISSUE THREAD

**Issue by TheAmanM** [KalleHallden/exer_log#124]
@KalleHallden It might be a good idea to implement [Firebase Crashlytics](https://firebase.google.com/docs/crashlytics) and [Performance monitoring](https://firebase.google.com/docs/perf-mon). These will give you good insight about your app on the Firebase console. 

Here is some sample code for implementing Crashlytics, it looks pretty simple:

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp();

  // Pass all uncaught errors from the framework to Crashlytics.
  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;

  runApp(MyApp());
}
```

**Comment by jorre127** [comment]
in addition to this we should probably also put the content of the main into a runeZonedGuard and catch and report the errors to firebase crashlytics.

**Comment by KalleHallden** [comment]
@all-contributors please add @TheAmanM for code, maintenance and

**Comment by TheAmanM** [comment]
Good point on the runZoneGuarded. The code, according to Firebase documentation should then be:

```dart
void main() async {
  runZonedGuarded<Future<void>>(() async {
    WidgetsFlutterBinding.ensureInitialized();
    await Firebase.initializeApp();

    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;

    runApp(MyApp());
  }, (error, stack) =>
    FirebaseCrashlytics.instance.recordError(error, stack, fatal: true));
}
```
Also @jorre127, how do you know so much about Flutter? Where do you learn everything from?

**Comment by jorre127** [comment]
@TheAmanM I work for a company that makes flutter apps, so that helps a lot haha. Just by coming into contact with it everyday I guess.
