### ISSUE TITLE
Remove the .git folder from the flutter folder

### ISSUE THREAD

**Issue by DobleV55** [KalleHallden/exer_log#13]
When you initially uploaded all the code, the flutter folder on your local machine has a .git folder inside, causing now a flutter folder that's seems empty and has that little icon in the github view.
I recommend to delete the .git folder inside the flutter folder and to commit-push again the contents of that folder, in case you don't want the content to be public on the repo, just add it to the .gitignore.
![Screenshot 2022-08-05 at 22 04 58](https://user-images.githubusercontent.com/24664579/183227564-163101fa-f03b-4b7e-894f-1c2ccaf448fb.png)

**Comment by KalleHallden** [comment]
I believe that this is being dealt with in #10 if not let me know!
