### ISSUE TITLE
Workouts not saved to database and historical workouts not show in calendar

### ISSUE THREAD

**Issue by mfederowicz** [KalleHallden/exer_log#130]
Hi iam trying to create new test workouts 
![test-workouts](https://user-images.githubusercontent.com/57678185/185790981-5589386f-3e73-4c4b-9d31-e880d8444cbb.png)

but after back to main screen on calendar there are no info about my workouts, just empty calendar

![home-calendar](https://user-images.githubusercontent.com/57678185/185791092-bf9ad570-295e-45de-bd9e-ee703c4052ab.png)

is it normal behaviour, or maybe persisting on database is not implemented yet?

**Comment by mfederowicz** [comment]
O course, Iam trying to sign out/sign in, and the results are the same :(

**Comment by ramsy0dev** [comment]
@mfederowicz  when saving the workout did you tap on this button
***
![Untitled](https://user-images.githubusercontent.com/86024158/185793072-2dd2a90f-e365-46e4-a003-b421a96d82e3.png)
***
if not then can you retry.

**Comment by mfederowicz** [comment]
![Screenshot_20220821_154820_com hallden exerlog](https://user-images.githubusercontent.com/57678185/185794096-93159df3-b612-4a9a-afa0-72a7606f4e70.jpg)
oooo ok, now its working, but only when you set rep > 0, maybe will be better to show accept sign only when user make required modifications in excersise settings?

**Comment by ramsy0dev** [comment]
Or a warning that pop up if the user made changes and accidentally tap on the back button

**Comment by mfederowicz** [comment]
yeah that wold be a good idea too )
