### ISSUE TITLE
Unit Tests For essential features

### ISSUE THREAD

**Issue by destrex271** [KalleHallden/exer_log#139]

**Comment by momshaddinury** [comment]
Before we can write unit tests we need good architecture. As of now, the code is not testable. But this is a good issue. We should hurry up with the transition.

Login and sign up are refactored. Calendar and Workout screen logic needs refactoring.

**Comment by destrex271** [comment]
So i think we can start preping up the required unit tests for the auth flow in the application, and while we are at it how about we add some flow diagrams to the readme as we progress with the developement?

**Comment by jorre127** [comment]
I think maybe we should only start adding unit tests when a page is done, and won't need to be changed much in the future. Because it's really annoying having to fix the tests again every time you make changes. The auth screens will probably get a redesign and with it might come some functional changes so I think we should wait till that's done.

**Comment by momshaddinury** [comment]
> I think maybe we should only start adding unit tests when a page is done, and won't need to be changed much in the future. Because it's really annoying having to fix the tests again every time you make changes. The auth screens will probably get a redesign and with it might come some functional changes so I think we should wait till that's done.

I agree

**Comment by destrex271** [comment]
> I think maybe we should only start adding unit tests when a page is done, and won't need to be changed much in the future. Because it's really annoying having to fix the tests again every time you make changes. The auth screens will probably get a redesign and with it might come some functional changes so I think we should wait till that's done.

Yup that sounds good
