### ISSUE TITLE
Mergeable not working now

### ISSUE THREAD

**Issue by tenshiAMD** [KalleHallden/exer_log#141]
Mergeable not working now after the repo got switched to an organization.

**Comment by momshaddinury** [comment]
I have sent an install request. @KalleHallden needs to approve it.

**Comment by KalleHallden** [comment]
I think I approved the request, lmk if there's something else that needs to be done on this end

**Comment by tenshiAMD** [comment]
I will be closing this issue now since mergeable is working as of the moment. Thanks everyone!
