### ISSUE TITLE
Provide Login feedback for users 

### ISSUE THREAD

**Issue by KalleHallden** [KalleHallden/exer_log#15]
# Create feedback for users
Logging in
- incorrect password
- incorrect email 
- email/account doesn't exist

Signing up
- email already exists
- passwords don't match
- password is too short

This issue is done when all of the above is completed. This feature should be worked on in the branch [Login ](https://github.com/KalleHallden/exer_log/tree/Login)

**Comment by HacDan** [comment]
I would recommend not specifying which item is incorrect when logging in. It provides information to bad actors that they don't need. 

For the signup process you'll need to notify if the email exists. But for the log in process not so much.

**Comment by KalleHallden** [comment]
Good point @HacDan!

**Comment by 0RaMsY0** [comment]
we can say at the login "wecome back $username"
i think that is what alot of apps do

**Comment by jorre127** [comment]
I believe this has already been merged, so maybe we should close this issue and continue in #64 for improvements?
