### ISSUE TITLE
Proposing to change license from MIT to GPLv3

### ISSUE THREAD

**Issue by PickleNik** [KalleHallden/exer_log#154]
[MIT](https://opensource.org/licenses/MIT) to [GPLv3](https://opensource.org/licenses/GPL-3.0)

Motivation behind this change: prevent proprietary derivative works.

The main reason for this change is to provide protection against the future distribution of the exer_log app in a proprietary form, while at the same time maintaining all of the freedoms to use, change or share the project which are currently in-place.

https://www.gnu.org/licenses/quick-guide-gplv3.html

What needs to be done for this:
- [x] All contributors to the codebase agree with the change.
- [x] Replace the main license file with GPLv3.

<img width="1241" alt="Screen Shot 2022-08-25 at 12 43 43 PM" src="https://user-images.githubusercontent.com/31113245/186722995-3632e25e-3462-40c5-bb36-c08d2243198a.png">

**Comment by lukelavery** [comment]
As far as I understand, the GPL licence will require anyone using this code to open source the project. This seems like a sensible change, to prevent others from using this code to make a profit. 

It may be useful to have an open discussion about any other licenses that are worth consideration

**Comment by PickleNik** [comment]
> to prevent others from using this code to make a profit.

This is __not__ correct and is a common misconception, all GPL open-source licenses allow for commercial use and distribution.
They do require any forks to be kept open-source, which means any modifications of and improvements to the app must be shared _**if**_ they are being distributed. So nobody can say, clone the repo, add a crypto miner or an IP grabber to it and publish it to the AppStore/PlayStore, if it is published any edits will need to be open-sourced.

To clear up any confusion, GPLv3 __does NOT__ prevent the app from being sold or monetized.

**Comment by lukelavery** [comment]
So the main benefit of a license like this would be to prevent improper use of the code? 

And do you have thoughts on using a more restrictive license that would prevent commercial use?

**Comment by PickleNik** [comment]
> So the main benefit of a license like this would be to prevent improper use of the code?

The main benefit is keeping changes and improvements open-source (that doesn't necessarily prevent improper use, but makes it more unlikely) and prevents from re-licensing code under a closed-source proprietary license which MIT allows for. 
> And do you have thoughts on using a more restrictive license that would prevent commercial use?

I'm personally not aware of any open-source license that prevents commercial use, when you do that it becomes more like source-available rather than open-source.

Here's a good resource made by Github:
https://choosealicense.com/licenses/gpl-3.0/
https://choosealicense.com/

And another good resource:
https://opensource.org/licenses/GPL-3.0

And here's a gist for it:
https://gist.github.com/kn9ts/cbe95340d29fc1aaeaa5dd5c059d2e60

**Comment by lukelavery** [comment]
I see, thank you for explaining.

Would love to hear @KalleHallden 's thoughts on this, and your motivations to open-source the project.

The prevention of re-licensing seems like an interesting idea to keep any code developed within the open-source community. MIT is possibly too permissive in this regard?

**Comment by PickleNik** [comment]
> MIT is possibly too permissive in this regard?

![image](https://user-images.githubusercontent.com/31113245/186782397-19e95f8a-18e7-4b13-a49d-81c4f4450e58.png)
here's a good diagram about that

**Comment by PickleNik** [comment]
@dinurymomshad @KalleHallden @tenshiAMD @mfederowicz 
I'd really appreciate your input on this :)

**Comment by mfederowicz** [comment]
@PickleNik i think that @KalleHallden as original author of this application, should decide about type of used license. To be honest iam only contributor, and I like develop/learn new things :)

**Comment by PickleNik** [comment]
True, but all contributors need to agree on this for him to change the license if decides that he wants to.

**Comment by KalleHallden** [comment]
@PickleNik I think this looks like the GPLv3 would be a suitable license to use. I just chose the MIT to have some sort of license that I have used before. So I'm happy to switch to GPLv3

**Comment by PickleNik** [comment]
Great, now we just have to make sure everyone's cool with it :)

@jorgelrj @TheAmanM @hannest03 @rachitkakkar @luca400 @aayushchugh @ckelwin @Bogdwynny @MhouneyLH @0RaMsY0 @md-siam @lukelavery @mfederowicz @tenshiAMD (sorry for the ping 😰)

Please 👍 if you're ok with this change

**Comment by 0RaMsY0** [comment]
@PickleNik yeah i think GPLv3 is a very good choice

**Comment by momshaddinury** [comment]
@PickleNik can you sort this out, please? I think everyone agrees

**Comment by PickleNik** [comment]
Looks like @jorgelrj @TheAmanM are the only remaining votes needed from people who contributed directly to the codebase and not to the outside files.

**Comment by momshaddinury** [comment]
Okay, let's wait one more day if we don't get any reply. Let's change it to GPLv3

**Comment by PickleNik** [comment]
I've reached out to @jorgelrj via email and I'm not sure how to reach @TheAmanM although they seem to be active on Github.

I am not a lawyer, but it seems like the contributions from both of them have been heavily edited to the point where it could be considered Fair Use, but a thumbs up for confirmation would still be appreciated from both regardless :)

**Comment by TheAmanM** [comment]
Woah, that's a lot of text!
Apologies for the lack of response. I will take a look at this in a few hours from now.

**Comment by TheAmanM** [comment]
@PickleNik All good with me!
