### ISSUE TITLE
Run build checks in every PR

### ISSUE THREAD

**Issue by tenshiAMD** [KalleHallden/exer_log#163]
We need this so we can be sure every PR does not break the build.

**Comment by tenshiAMD** [comment]
I will do this later.

**Comment by luca400** [comment]
Have you started on it or can I give it a go?

**Comment by tenshiAMD** [comment]
@luca400 yes I already started it on my end and I was just busy these past few days in order to complete it.

**Comment by tenshiAMD** [comment]
@all-contributors please add @mfederowicz  for bug
