### ISSUE TITLE
Request to create a website for this open-source project

### ISSUE THREAD

**Issue by aayushchugh** [KalleHallden/exer_log#174]
We can also develop a react website and share the database and implement same features in the website
so that everyone can use this app who don't have IOS device

**Comment by tenshiAMD** [comment]
@aayushchugh yes great suggestion but I think we need to focus on completing android first. If someone does not have iOS then I assume they use android instead.

**Comment by aayushchugh** [comment]
@tenshiAMD We can do both, because this is a big community and people would like to contribute in both of them

**Comment by tenshiAMD** [comment]
@aayushchugh yes that's correct, also the final decision is up to @KalleHallden which ones are the most priority. He is currently developing a great plan for this project.

**Comment by jorre127** [comment]
@aayushchugh A website would be nice, but wouldn't it make sense to also use flutter for that? This way we don't need to have an entire separate project and can just tweak the ui for web.

**Comment by aayushchugh** [comment]
@jorre127 but there is a big community for react

**Comment by tenshiAMD** [comment]
@aayushchugh I agree with @jorre127 since flutter already can do web too

**Comment by KalleHallden** [comment]
@aayushchugh I’m not sure what you mean since the app works on android, so it’s not an IOS only app? 
the only reason to create a website would be so that people can run the app on a laptop? But in that case I think it would make more sense to do what @jorre127  suggests which is sticking with flutter. We would hardly need to make any changes I believe in order to run it in a browser :)

**Comment by aayushchugh** [comment]
@tenshiAMD but if we will do Android than we can use react native and react for website

**Comment by aayushchugh** [comment]
@KalleHallden we can do that

**Comment by aayushchugh** [comment]
My bad I didn't realised that flutter also works on Android 🙂

**Comment by aayushchugh** [comment]
No sure should I close this as completed or not planned. I am closing this as not planned for now because we didn't write any code or made actual contribution
