### ISSUE TITLE
Add stalebot to manage stale and irrelevant PRs and issues

### ISSUE THREAD

**Issue by tenshiAMD** [KalleHallden/exer_log#179]
I suggest adding [stalebot](https://github.com/apps/stale) so we can manage stale and irrelevant PRs and issues.

**Comment by tenshiAMD** [comment]
I can do this later. @EXERLOG/maintainers are you cool with it? Let me know. Thanks!

**Comment by aayushchugh** [comment]
@tenshiAMD We should also add [Repository Commander](https://github.com/marketplace/shriproperty-bot)

I am actively maintaining this project this will help in label automation and use of `/slash` commands in comments
I am also working on some another features and will release them soon

I can also add/change features based on requirements

**Comment by tenshiAMD** [comment]
> @tenshiAMD We should also add [Repository Commander](https://github.com/marketplace/shriproperty-bot)

@aayushchugh Thanks for letting us know. We will review if we can use it based on our use cases.

**Comment by momshaddinury** [comment]
> I can do this later. @EXERLOG/maintainers are you cool with it? Let me know. Thanks!

This is nice. We do have lots of issues popping up.

**Comment by aayushchugh** [comment]
@tenshiAMD I have implemented the functionality in bot that it will ask for more information on issues if the body is less than 20 characters long

 
![Screenshot 2022-09-05 185937](https://user-images.githubusercontent.com/69336518/188549403-563dfcaf-d942-45f0-905e-0585d7656267.png)


These features are not configurable yet but in next release I will make everything configurable

**Comment by tenshiAMD** [comment]
> @tenshiAMD I have implemented the functionality in bot that it will ask for more information on issues if the body is less than 20 characters long

@aayushchugh thanks for letting us know however we already using `mergeable`. FYI, we can set up the same use case with it.

**Comment by tenshiAMD** [comment]
> This is nice. We do have lots of issues popping up.

@dinurymomshad alright then let's implement it. 😄

**Comment by tenshiAMD** [comment]
@KalleHallden please install stale by following [this guide](https://github.com/apps/stale)
