### ISSUE TITLE
Proposal to add issue templates

### ISSUE THREAD

**Issue by aayushchugh** [KalleHallden/exer_log#184]
here is example

https://github.com/shriproperty/server/issues/new/choose

**Comment by tenshiAMD** [comment]
@aayushchugh thanks for the suggestion. We will be adding templates soon.

**Comment by aayushchugh** [comment]
@tenshiAMD if you want I can add them

**Comment by aayushchugh** [comment]
@tenshiAMD if you want I can add them

assign this issue to me

**Comment by tenshiAMD** [comment]
> @tenshiAMD if you want I can add them

@aayushchugh Actually, I already have some prepared templates here. Also, anyone can post an issue without a template for now then we can ask them for additional details. We may need to discuss this internally.
