### ISSUE TITLE
Please add logo to @EXERLOG organization

### ISSUE THREAD

**Issue by aayushchugh** [KalleHallden/exer_log#185]
@KalleHallden currently there is no logo on organization profile. I would recommend adding the logo as avatar on profile

**Comment by tenshiAMD** [comment]
@aayushchugh Yes, correct. We will be adding it soon. Thanks for the reminder.

**Comment by tenshiAMD** [comment]
@aayushchugh I will close this one since it's irrelevant for this repo. I already ping @KalleHallden in our org discussion. Thanks! :tada:
