### ISSUE TITLE
Firebase configuration

### ISSUE THREAD

**Issue by randomGithubAccount2** [KalleHallden/exer_log#206]
**Steps to reproduce**
Fetch any data from the database

**Expected behavior**
User should only have access to own files

**Actual behavior**
Once logged in as any user, you can access any file in the database (see attached video) and hereby personal data of other users

**Other Information**
You should set up access restrictions for firebase, maybe using cloud functions or something like that.

_Also, you should prevent third party use of your API key by configuring who can use it. For an Android app, you can specify that your API Key can be used only by an Android application that has been signed by a given keystore and using a given package name, because right now everyone can make an app using your firebase services._

https://user-images.githubusercontent.com/103576816/193455760-8f04ef24-8b79-4bdc-8823-dfb82e3f80b4.mp4

**Comment by k-rokicki** [comment]
Is this resolved? This is a pretty bad GDPR violation...

**Comment by randomGithubAccount2** [comment]
> Is this resolved? This is a pretty bad GDPR violation...

Considering this issue has been pretty much ignored probably no. The whole repo seems to be very unmaintained
