### ISSUE TITLE
Cannot say no in `Delete workout` confirmation dialog

### ISSUE THREAD

**Issue by ckelwin** [KalleHallden/exer_log#24]
There is no option to cancel or choose `No` in the delete workout confirmation dialog.

To add: A `Cancel` or `No` button to the popup.

![image](https://user-images.githubusercontent.com/5429312/183301146-c89b13dc-502e-4d0c-9690-1b3e7d2a238b.png)

**Comment by ckelwin** [comment]
I'll close this as it's possible to press the `Back` button. I tested on the emulator and did not try it out the first time.

**Comment by HaardikBhagtani** [comment]
@ckelwin, wouldn't it be better to have a `Cancel` Button along with a `Delete` Button? Wouldn't it better the UX?

**Comment by ckelwin** [comment]
@HaardikBhagtani I have no strong preference one way or another. I only need a way to 'go back' or cancel and I found it. It could be good UX to include a `Cancel` button.

@KalleHallden What do you think? Should it be included? If so, we can reopen this issue.
