### ISSUE TITLE
README.md and LICENSE and .gitnore

### ISSUE THREAD

**Issue by Programmer-RD-AI** [KalleHallden/exer_log#4]
Hi,
It seems that the repo doesn't have a README.md and LICENSE and .gitnore. So It would be useful to have those files for new contributors to know what the project is about and etc...

**Comment by KalleHallden** [comment]
Hi! Not sure what you mean, it does have README and LIcense. Is the apache license more suitable for the project than an MIT?
Other than that I think we have everything. .gitignore I have, but maybe it's been removed so not sure?

**Comment by Programmer-RD-AI** [comment]
Hi,
I created this issue 5 days ago. So this is outdated. 
I am sorry for the confusion.
With best regards,
Ranuga

**Comment by KalleHallden** [comment]
Okay I see, no worries!
