### ISSUE TITLE
Discussion Section

### ISSUE THREAD

**Issue by Programmer-RD-AI** [KalleHallden/exer_log#6]
Hi,
I think it would be useful to have a discussion section, so other contributors can discuss about the project.

**Comment by KalleHallden** [comment]
Great idea!

**Comment by KalleHallden** [comment]
I've created a [project board](https://github.com/users/KalleHallden/projects/1/views/1) to five some idea as to what needs to be done first and where we are at with certain things

**Comment by Programmer-RD-AI** [comment]
I think the project board is really useful. And a good way for other contributors to know the future and the goals of the project. I think it is similar to the discussion section and generally better. So I will close this GitHub issue.
With best regards
