### ISSUE TITLE
Automation: Add workflow for automatically create new release when pull request is merged into main branch (I can do that)

### ISSUE THREAD

**Issue by aayushchugh** [KalleHallden/exer_log#63]
I think that we should have a workflow in this repo which will automatically create new release on every pull request merged into
main branch. but we have to follow some strict steps to implement this 

- Create new `dev` branch and set it to default
- Every one should follow `conventional commits` eg:- `feat(login): ✨ added feedback for users`
- Use `semantic release` for creating new release (this is help in automatically create release)

I can implement the workflow. but asking for permission to do so

**Comment by KalleHallden** [comment]
Yeah this would be a great thing to implement. I have created a branch called [alpha](https://github.com/KalleHallden/exer_log/tree/alpha) that I think we can use instead of the dev branch. Unless you think that dev would be a more conventional name that would be more suitable?

**Comment by aayushchugh** [comment]
I will start working on this now. I think `alpha` will be good name

**Comment by aayushchugh** [comment]
@KalleHallden I have completed the task but I am not sure If I should submit pull request in `master` or `alpha`
Please tell me in which branch I should create pull request

**Comment by aayushchugh** [comment]
`Alpha` is behind `master` I think you should update that and than I will create pull request in `alpha` only

**Comment by aayushchugh** [comment]
@KalleHallden I have completed the task. but I can't create pull request in `master` because If you merge that, It will trigger action to create new release and `alpha` branch is behind master so I think that you should update `alpha` with `master` first. Than I will create new pull request in `alpha`

**Comment by KalleHallden** [comment]
Alright I think I have done that now :)

**Comment by KalleHallden** [comment]
What does the personal access token need in terms of access?

**Comment by aayushchugh** [comment]
I granted these permissions duringtesting

![image](https://user-images.githubusercontent.com/69336518/185136237-af15225d-0c59-4026-a6f9-1caae4dca4c0.png)
![image](https://user-images.githubusercontent.com/69336518/185136336-4ab04144-11a0-42e0-a395-885f5c633e16.png)

**Comment by KalleHallden** [comment]
Alright it has been added

**Comment by aayushchugh** [comment]
Should I close this issue or you will do that ?
