### ISSUE TITLE
Can we have the option to add designated reviewer for the time being?

### ISSUE THREAD

**Issue by dinurymomshad** [KalleHallden/exer_log#66]
### Would really like a discussion section. (https://docs.github.com/en/discussions)

How are we planning to make sure, people can add others as reviewers? I can't add anyone for review. Given we have a structure in place, we should have the option to add people as reviewers.

**Comment by KalleHallden** [comment]
Great idea [discussion](https://github.com/KalleHallden/exer_log/discussions/67) here.

**Comment by dinurymomshad** [comment]
Nice. Thanks, @KalleHallden
