### ISSUE TITLE
Change the instruction in the README.md on how to build the app

### ISSUE THREAD

**Issue by 0RaMsY0** [KalleHallden/exer_log#70]
It not a big thing but you should remove or replace this line from the [README](https://github.com/KalleHallden/exer_log/edit/master/README.md)
from 

CD into the project
``` bash
  cd exer_log/app/exerlog
```
to 

CD into the project

```bash
  cd exer_log
```
because the app source code is no longer inside of the ```app/exerlog```

**Comment by dinurymomshad** [comment]
@0RaMsY0 good catch. Feel free to open a PR on it.
