### ISSUE TITLE
BUG: Showing the calendar-screen briefly followed by a black-screen with loading indicators before navigating to the workout-screen after login

### ISSUE THREAD

**Issue by momshaddinury** [KalleHallden/exer_log#86]
**Steps to reproduce**:

1. Logout if you are logged in.
2. Close and remove the app from recent. Restart the app
3. Login with valid credentials
4. Notice that for a brief period showing the calendar screen followed by a black screen before navigating to the workout screen

_Expected_: After login, the user should navigate to the Workout screen

**Video**
https://user-images.githubusercontent.com/26508767/185309898-c277614a-a435-40ea-becf-a15489c75c1d.mp4

**Comment by momshaddinury** [comment]
@KalleHallden I know what is causing this issue. But before solving it we need to define navigation logic. Right now a user navigates to the workout screen on login/signup. 
But I vote for the following:
1. Upon signing up - Navigate the user to workout screen
2. Upon login - Navigate the user to calendar screen

Proposed solution:
With the help of a login boolean flag, we can check if a user is logged in or not. So in the splash screen, we can check if the logged-in flag is true. If it is true, we navigate the user to the calendar screen. Otherwise, we navigate the user to the landing screen.

**Comment by momshaddinury** [comment]
@ckelwin @jorre127 please have a look.

**Comment by KalleHallden** [comment]
Yeah I agree with that flow of events as well, seems to make the most sense

**Comment by jorre127** [comment]
@dinurymomshad @KalleHallden Yeah that flow seems good to me. Is this issue partially the same as #40? because if so we should probably close that issue.

**Comment by momshaddinury** [comment]
Most probably. Alright on it. Thanks, @jorre127.

**Comment by momshaddinury** [comment]
@jorre127 yes, I initially thought the black screen loading was caused by how I was handling `authStateChanges()`. But this #40 is what causing the issue. I will solve that as well.
