### ISSUE TITLE
Getting a StateError (bad state) when creating a new workout

### ISSUE THREAD

**Issue by ramsy0dev** [KalleHallden/exer_log#89]
Whene creating a New Worckout after providing the name of it 
i get an exception that says the following: 
***
![Screenshot from 2022-08-18 15-12-54](https://user-images.githubusercontent.com/86024158/185417982-6af08911-4688-46e0-814b-434083729c74.png)

(the file that has the Exeption is [this one](https://github.com/KalleHallden/exer_log/blob/alpha/lib/Bloc/max_bloc.dart))
***

**Comment by momshaddinury** [comment]
Can you add a video and steps to reproduce? @0RaMsY0

**Comment by ramsy0dev** [comment]
For some reason my recording software is not working but i am gonna try and tell you steps 
so when you are in the home page and click on "Start a new workout" then you get to an auther page that pops up a TextField 
 where you type  an exercie name wich is this one 

![Screenshot_20220818-200838](https://user-images.githubusercontent.com/86024158/185475848-87ba63a1-9623-4df0-ab60-23c5cef2dd41.png)

when you create on add this exercise get added like i see it here

![Screenshot_20220818-195436](https://user-images.githubusercontent.com/86024158/185476103-e767a454-cec8-4259-b786-301cd286dceb.png)
and then i get the Exeption in vs code

**Comment by 0RaMsY0** [comment]
i found that 
``` dart
QuerySnapshot<Map<String, dynamic>>? ref;
  ref = await FirebaseFirestore.instance
      .collection('users')
      .doc(userID)
      .collection('maxes')
      .where('exercise', isEqualTo: exercise)
      .orderBy('weight', descending: true)
      .get();
```
dons't have any element and we shouldn't be checking if it null in line 58
we should check if it is not an empty array i did that with the following
``` dart
//i changed ```ref != null``` to this
 if (ref.docs.isNotEmpty) {
    returnMax = Max.fromJson(ref.docs.first.data());
  } else {
    returnMax = new Max(0, 0, 0, '');
  }
  return returnMax;

```

i did that and now i get a new problem  here it is :
![Screenshot from 2022-08-18 20-39-06](https://user-images.githubusercontent.com/86024158/185480122-8b4fda69-19dc-4ff9-b3fb-103d85937fca.png)

**Comment by 0RaMsY0** [comment]
i think i found what makes this Exception get thrown 
the bug is in the line 36 in [max_builder.dart](https://github.com/KalleHallden/exer_log/blob/alpha/lib/UI/maxes/max_builder.dart) because i think there we are checking for an error to calculate percentage from the user enerted data but there well be no error since the function that the StreamBuild uses wich is getOneRepMax() will return  
``` dart 
Max(0, 0, 0, '')
```
in case it didn't found it in the Firebsae
and that is not error so it well calculate the percentage from that returned data wich is ``` Max(0, 0, 0, '') ``` and then all this Exception will be raised.
if anybody can fix this then go a head i couldn't since i'm just a beginner and i spend alot of time just to figure this out and imay wrong about i don't know.

**Comment by ramsy0dev** [comment]
i fixed this issue in #96

**Comment by KalleHallden** [comment]
@0RaMsY0 how come you closed #96?

**Comment by ramsy0dev** [comment]
@KalleHallden I thaught i was already fixed by someone else,
i have reopened it

edit: @jorre127 and i are still discussion this issue and we are not sure if what i did will actually fix this issue

**Comment by jorre127** [comment]
@0RaMsY0  I looked into it and fixed the problem, problem is then I got a lot of different errors haha. Seeing as the workout page is going to be reworked anyway in the transition to riverpods, I don't think it's useful to try and fix all the errors right now. It's better to just redo it I think. If you agree I'm going to close the PR for now.

**Comment by ramsy0dev** [comment]
@jorre127 alright you can close it thanks for your help

**Comment by ckelwin** [comment]
@jorre127 I've not been able to create workout for a while now. The calendar widget does not show a clickable day icon after creating the workout. Having trouble logging in as well (login button turns into spinner forever). I don't know if it's something wrong with my local or the code.

I'll create a separate issue for the login if no one has done so. Not sure if the problem I'm facing with cannot creating workout is similar to this issue. 
My issue: https://github.com/EXERLOG/exer_log/discussions/90#discussion-4314895

**Comment by jorre127** [comment]
@ckelwin does the workout that doesn't show up on the calendar have zero reps? Because maybe it has something to do with #130

**Comment by ckelwin** [comment]
@jorre127 Attached a screen recording. 

https://user-images.githubusercontent.com/5429312/187013156-4671b7e5-db28-4844-a098-22772c6bf620.mp4

**Comment by ckelwin** [comment]
I was having the said problem with creating and/or viewing workouts when using an emulator. Switched to a physical device and it's working fine now. Much faster as well.

**Comment by MhouneyLH** [comment]
> I was having the said problem with creating and/or viewing workouts when using an emulator. Switched to a physical device and it's working fine now. Much faster as well.

I have the same issue. Did you find out, why it doesn't work on the emulator?
I get the following error with the emulator:

![image](https://user-images.githubusercontent.com/78447003/187776121-507b36a3-d82a-43ed-a5d0-98330657b17e.png)
