### ISSUE TITLE
Git directory structure

### ISSUE THREAD

**Issue by edrisranjbar** [KalleHallden/exer_log#9]
I think we should put **Git** on the main directory where the `.README` file exists. so that when users come to the _repo_ get a gist of the project and can read the DOCS we want them to read.
so instead of going to `/app/exerlog` user sees the project after `cloning the project`. **notice that we clone a repo it automatically will be extracted within a directory with the same name as the `repo name`**

and also it would be great to add a explicit steps to run the app for the sake of running the app easier; so that they can follow the process of installation based on a guide.

**Comment by KalleHallden** [comment]
Great idea I think this is being dealt with or will be dealt with after #10

**Comment by MarkusZoppelt** [comment]
PR #56 fixes this. Please merge if possible.
