### ISSUE TITLE
Minor calendar widget improvement

### ISSUE THREAD

**Issue by TheAmanM** [KalleHallden/exer_log#98]
The calendar widget could be modified to show a single centered, ideally larger `CircularProgressIndicator()`, Right now, it shows 35 `CircularProgressIndicator()` simultaneously. 

As of now, this is what the widget looks like. 
![Screenshot_2022-08-19_23-53-03](https://user-images.githubusercontent.com/75181008/185699328-b6c5961a-a197-41aa-8f3e-bc70f8dac52e.png)

**Comment by KalleHallden** [comment]
Yes this is a great issue!
